name: Notify Pipeline Status

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types: [completed]

jobs:
  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Notify Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "✅ Pipeline executada com sucesso!"
          echo "Build: ✅"
          echo "Lint/Format: ✅"
          echo "Tests: ✅"

      - name: Notify Failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "❌ Pipeline falhou!"
          echo "Verifique os logs para mais detalhes."
